export type OfficialClientObservation = Readonly<{runId: string; projectRef: string; origin: string}>;
export const OFFICIAL_ISOLATION_MODE: "NEW_EMPTY_TEST_ONLY_PROJECT_V1";
export const OFFICIAL_PROVIDER_RETENTION: "RETAIN_RUN_OWNED_VERCEL_PREVIEW_AND_ENVIRONMENT_V1";
export const OFFICIAL_PREVIEW_ENVIRONMENT_KEYS: readonly string[];
export const OFFICIAL_ISOLATION_KEYS: readonly string[];
export const ADMIN_V1_OFFICIAL_ISOLATION_CONTRACT_V1: Readonly<{
  schema_version: 1;
  operation_class: "ADMIN_V1_OFFICIAL_RUNTIME_V1";
  mode: typeof OFFICIAL_ISOLATION_MODE;
  provider_cleanup_policy: typeof OFFICIAL_PROVIDER_RETENTION;
  origin_relation: "HTTPS_PROJECT_REF_DOT_SUPABASE_DOT_CO_V1";
  allow_custom_origin: false;
  excluded_project_ref: "mtpisopvdxuvmpzbzqjw";
  excluded_origin: "https://mtpisopvdxuvmpzbzqjw.supabase.co";
  environment_keys: readonly string[];
  credential_bundle_schema_version: 1;
  credential_bundle_provenance_source: "OWNER_BOUND_ISOLATED_BUNDLE_V1";
  credential_value_names: readonly string[];
  credential_value_max_bytes: 16384;
  provisioning_receipt_schema_version: 1;
  provenance_receipt_schema_version: 1;
  expected_preview_project_id: "prj_BPaQVKdElriAhxabhoTkg8LysQ5R";
  expected_preview_team_id: "team_9POJYxNnjIBbrQ19My8M5yG3";
}>;
export const ADMIN_V1_OFFICIAL_ISOLATION_CONTRACT_SHA256: string;
export class OfficialIsolationError extends Error { readonly code: string; }
export function canonicalOfficialOrigin(value: unknown): string;
export function boundOfficialOrigin(projectRef: unknown, origin: unknown): string;
export function requireOfficialLifetime(authorization: unknown, nowEpochMs: number): number;
export function validateOfficialIsolationAuthorization(authorization: unknown, nowEpochMs: number): Readonly<Record<string, unknown>>;
export function validateOfficialProvisioningReceipt(authorization: unknown, receipt: unknown, nowEpochMs: number): Readonly<Record<string, unknown>>;
export function observeOfficialClientOrigin(input: {runId: unknown; projectRef: unknown; actualClientOrigin: unknown}): OfficialClientObservation;
export function validateOfficialIsolationBinding(input: {authorization: unknown; localObservation: unknown; previewObservation: unknown; provisioningReceipt: unknown; nowEpochMs: number}): Readonly<{status: "EXACT_ISOLATED_BINDING"; runId: string; projectRef: string; origin: string}>;
